import { NextResponse } from "next/server";
import { streamAgentResponse, getDefaultModel } from "@/lib/agent";
import readEnv from "@/lib/config";

const env = readEnv();

// Helper to determine if a local model supports chat completions
async function supportsChat(modelName: string): Promise<boolean> {
  if (modelName.startsWith("mock-")) return true;
  try {
    const res = await fetch(`${env.ollamaHost}/api/show`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ model: modelName }),
    });

    if (!res.ok) return false;
    const data = await res.json();

    // Verify chat capability using Ollama's capabilities array
    const capabilities = data.capabilities || [];
    if (!capabilities.includes("completion")) {
      return false;
    }
    return true;
  } catch {
    return false;
  }
}

export async function POST(req: Request) {
  try {
    const { content, threadId, model } = await req.json();

    if (!content) {
      return NextResponse.json({ error: "Missing content" }, { status: 400 });
    }

    const activeThreadId = threadId ?? "default-session";
    const targetModel = model || (await getDefaultModel());

    // Pre-validate that the chosen model actually supports chat
    const isChatSupported = await supportsChat(targetModel);
    if (!isChatSupported) {
      return NextResponse.json(
        { error: `Model "${targetModel}" does not support chat completions.` },
        { status: 400 }
      );
    }

    // Intercept simulated mock models for offline testing
    if (targetModel.startsWith("mock-")) {
      const encoder = new TextEncoder();
      const mockStream = new ReadableStream({
        async start(controller) {
          const sentences = [
            "<think>\nThis is a mock reasoning process generated dynamically by the offline simulated model. The UI elements and Settings Model panel configurations have been verified.\n</think>\n",
            `Hello there! This is a simulated response generated by the simulated test model **"${targetModel}"**.\n\n`,
            "This model is running offline for demonstration and testing purposes. All chat controls, message view scrollings, layout settings, and color palettes are completely active and responsive.\n\n",
            "Feel free to switch models, modify appearance parameters, or add other mock models in the Model Management tab to test further details!",
          ];

          for (const sentence of sentences) {
            const words = sentence.split(" ");
            for (const word of words) {
              controller.enqueue(encoder.encode(word + " "));
              await new Promise((r) => setTimeout(r, 45));
            }
          }
          controller.close();
        },
      });

      return new Response(mockStream, {
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "Cache-Control": "no-cache",
          "Connection": "keep-alive",
        },
      });
    }

    // Call the streamAgentResponse from lib/agent.ts
    const stream = streamAgentResponse(content, activeThreadId, targetModel);

    return new Response(stream, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
      },
    });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } catch (error: any) {
    console.error("Chat API error:", error);
    return NextResponse.json(
      { error: error.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}
